url: http://www.kuragestudios.com
baseurl: 

# Site settings
title: Kurage Studios
email: kuragestudios@gmail.com
description: "Indie Game Company"
google-analytics: "UA-653994-8"
facebook-admin-id: 10153567127088483

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
socials:
  - name: twitter
    title: Twitter
    url: https://twitter.com/kuragestudios/
  - name: facebook
    title: Facebook
    url: https://www.facebook.com/KurageStudios/

# Postal address (add as many lines as necessary)
address:
  - line: Tokyo, Japan

# Stores
stores:
  app-store:
    title: App Store
    image: /images/appstore_get_it.jpg
  google-play:
    title: Google Play
    image: /images/googleplay_get_it.jpg

# Additional collections
collections:
  - sections
  - games
  - timelines
  - members

# Build settings
markdown: kramdown
permalink: pretty
